// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoAPI.Data;

#nullable disable

namespace ProjetoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ProjetoAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContatoResponsavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistroAluno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TurmaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContatoResponsavel = "11999990001",
                            Nome = "Vinícius",
                            RegistroAluno = "RA1001",
                            TurmaId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContatoResponsavel = "11999990002",
                            Nome = "Julio",
                            RegistroAluno = "RA1002",
                            TurmaId = 1
                        },
                        new
                        {
                            Id = 3,
                            ContatoResponsavel = "11999990003",
                            Nome = "João Pedro",
                            RegistroAluno = "RA1003",
                            TurmaId = 1
                        },
                        new
                        {
                            Id = 4,
                            ContatoResponsavel = "11999990004",
                            Nome = "Luiz Felipe",
                            RegistroAluno = "RA1004",
                            TurmaId = 1
                        });
                });

            modelBuilder.Entity("ProjetoAPI.Models.MotivoInfracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MotivosInfracao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Uso de celular em sala de aula",
                            Gravidade = "Leve"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Desrespeito ao professor",
                            Gravidade = "Grave"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Briga com colega",
                            Gravidade = "Grave"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Atraso recorrente sem justificativa",
                            Gravidade = "Médio"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Perturbação do andamento da aula",
                            Gravidade = "Leve"
                        });
                });

            modelBuilder.Entity("ProjetoAPI.Models.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("MotivoInfracaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("MotivoInfracaoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("ProjetoAPI.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disciplina = "Matemática",
                            Matricula = "MAT001",
                            Nome = "Prof. Carlos Silva"
                        },
                        new
                        {
                            Id = 2,
                            Disciplina = "Português",
                            Matricula = "POR002",
                            Nome = "Profa. Ana Souza"
                        },
                        new
                        {
                            Id = 3,
                            Disciplina = "História",
                            Matricula = "HIS003",
                            Nome = "Prof. Marcos Pereira"
                        });
                });

            modelBuilder.Entity("ProjetoAPI.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Turmas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoLetivo = 2026,
                            Nome = "3º Ano - EE. Prof Theodorico de Oliveira",
                            Turno = "Manhã"
                        });
                });

            modelBuilder.Entity("ProjetoAPI.Models.Aluno", b =>
                {
                    b.HasOne("ProjetoAPI.Models.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ProjetoAPI.Models.Ocorrencia", b =>
                {
                    b.HasOne("ProjetoAPI.Models.Aluno", "Aluno")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAPI.Models.MotivoInfracao", "MotivoInfracao")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("MotivoInfracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAPI.Models.Professor", "Professor")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("MotivoInfracao");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ProjetoAPI.Models.Aluno", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("ProjetoAPI.Models.MotivoInfracao", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("ProjetoAPI.Models.Professor", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("ProjetoAPI.Models.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
